k3s_version: v1.22.2+k3s1
ansible_user: root
systemd_dir: /etc/systemd/system
master_ip: "10.20.20.51"
extra_server_args: "--write-kubeconfig-mode=644"
extra_agent_args: ""
copy_kubeconfig: true
metallb: false
metallb_version: "v0.12.1"
metallb_range: "192.168.3.93-192.168.3.94"
argocd: false
argocd_service_type: LoadBalancer
dns_servers: []
